spring.application.name=craftverse-blog-api

# Server Configuration
server.port=5000
server.servlet.context-path=/api

# Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/craftverse_blog
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Connection Pool Configuration
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5971
jwt.access-token-expiration-ms=86400000