spring.application.name=craftverse-blog-api

# Server Configuration
server.port=5000
server.servlet.context-path=/api

# Datasource Configuration
spring.datasource.url=jdbc:postgresql://192.168.0.6:5432/craftverse_blog
spring.datasource.username=datakeeper
spring.datasource.password=moostar3829

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool Configuration
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5971
jwt.access-token-expiration-ms=86400000

# RabbitMQ ??
spring.rabbitmq.host=192.168.0.6
spring.rabbitmq.port=5672
spring.rabbitmq.username=datakeeper
spring.rabbitmq.password=moostar3829

# RabbitMQ ?, ?????, ??? ? ??
rabbitmq.queue.email.name=email.queue
rabbitmq.exchange.name=email.exchange
rabbitmq.routing.email.key=email.routing.key

# ??? ??
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dev.hr.kim@gmail.com
spring.mail.password=pcawvwqurzlngchd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis ??
spring.redis.host=192.168.0.6
spring.redis.port=6379
spring.redis.password=moostar3829
spring.redis.timeout=60000

# Google OAuth2 ??
spring.security.oauth2.client.registration.google.client-id=849712122070-d0qt0uutvjna1s115j0a92r5nqugrkhb.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:5000/api/auth/google/callback

# ?????? ??
app.auth.frontend-redirect-uri=http://localhost:5173/auth/callback
app.auth.token-secret=cRaFtVeRsE_BlOg_S3cR3t_K3y_2025_SECURE_TOKEN_STRING_8273645917
app.auth.token-expiration-ms=86400000

# ?? ?? ??
server.servlet.session.timeout=86400

logging.level.kr.co.craftverse.craftverse_blog_api: DEBUG
logging.level.org.springframework.security: DEBUG

toss.payments.secret-key: live_sk_oEjb0gm23Pyv75QgngjgVpGwBJn5
toss.payments.success-url:: http://localhost:5173/payment/success
toss.payments.fail-url:: http://localhost:5173/payment/fail
toss.payments.webhook-url:: https://e30a-112-214-124-39.ngrok-free.app/payments/webhoo